### ISSUE TITLE
Error when integrating for STM32

### ISSUE THREAD

**Issue by Devilscave** [RobTillaart/TLC5917#3]
Sorry that I'm just getting back to you now, I haven't gotten around to working on the project for a while.

So I have now tried to port the project to a SMT32F030P, with the STM modification specified by them it also works, only then nothing happens anymore.
I have also tried it on a Nano V3 and a LGTBF328 in the original, but then only if they still work. 
In any case, with your mod for STM32, not a single output works just by including the "#include TLC5917.h". No LED nothing only the standard serial still works. Do I have to replace the Y & X in your example with something? I just copied it as you put it in.

**Comment by RobTillaart** [comment]
No need to apologize, 

As I am out of context I dug up the other issues, need to reread them as they are "many thousands lines of code" ago.
- https://github.com/RobTillaart/TLC5917/issues/2
- https://github.com/RobTillaart/TLC5947/issues/5
- https://github.com/RobTillaart/TLC5947/issues/6

**Comment by Devilscave** [comment]
I meant this section from 

> discuss and test TLC5917 initial release [#8](https://github.com/RobTillaart/TLC5917/issues/2#issuecomment-2041419720)

```
// #include "Arduino.h"     <<<< disabled that one and the next includes solves the uint8_t , calloc and free.
#include <stdint.h>
#include <cstdlib>

//  these are the functions you need to have
#define pinMode(X, Y)        {}
#define digitalWrite(X, Y)   {}
#define digitalRead(X)       (1)

// and some constants
#define HIGH    1
#define LOW     0
#define OUTPUT  0
```

However, if I now only add the line `#include "TLC5917.h"` to my code, no outputs/inputs on the STM32 work any more. All ports are blocked, or presumably no longer defined.

**Comment by RobTillaart** [comment]
That was my patch to get the library compiling for STM32 but as I have no hardware I can not test its behavior runtime.

### What to do

When compiling for STM32 it complains about **Arduino.h** so that needs to be removed.

Then new error messages pop up and they need to be tackled one by one as that is the only way remote debugging works.

So include the library as is in your project and only comment the line **#include Arduino.h**
What is the first error the compiler produces?

**Comment by Devilscave** [comment]
Sorry, due to a small paragraph error in 
3# issuecomment-2103492461 (please read again)
The source code was not displayed correctly.
Of course I have hidden the `#include “Arduino.h”`.
It also compiles without errors and I can transfer it to the STM32.
But as already mentioned no more outputs work e.g. blink example no more.
So even if I don't need the `"TLC5917.h"` in the standard blink example, but add it anyway, the LED output to BUILTLED no longer works. Which for me is probably due to a port name interrupt or assignment of the ports.

But I must also say that I do not use the usual STM32, in my application an TSSOP20 is used for the special design, chip type: STM32F030F4P6
Test on the STM32F030 Demo Board v1.1
![STM32F030 Demo Board](https://github.com/RobTillaart/TLC5917/assets/39168213/ee34e6d4-065e-4e8a-a02b-4f816b4ed779)

**Comment by RobTillaart** [comment]
This is the list of STM32 I have installed. Which to use?

![image](https://github.com/RobTillaart/TLC5917/assets/462844/62787b39-8723-4d0c-9503-4bfefee1bc17)

**Comment by RobTillaart** [comment]
> Of course I have hidden the #include “Arduino.h”.
It also compiles without errors and I can transfer it to the STM32.
But as already mentioned no more outputs work e.g. blink example no more.

So you say you need the "Arduino.h" include?

OK then you should not remove it from the TLC4917 library either.

**Comment by Devilscave** [comment]
![329518963-62787b39-8723-4d0c-9503-4bfefee1bc17](https://github.com/RobTillaart/TLC5917/assets/39168213/ac5c8991-2a8b-48a6-af89-1c233d0b734a)

3 higher

> So you say you need the "Arduino.h" include?

NO, currently not

**Comment by RobTillaart** [comment]
STM32F030 => TLC5917_demo.ino compiles as is.

Sketch uses 13948 bytes (85%) of program storage space. Maximum is 16384 bytes.
Global variables use 1228 bytes (29%) of dynamic memory, leaving 2868 bytes for local variables. Maximum is 4096 bytes.

**Comment by RobTillaart** [comment]
@Devilscave 
Do you know this library? - https://github.com/Andy4495/TLC591x

Did not look into the details but it seems to be quite mature.

**Comment by Devilscave** [comment]
> @Devilscave Do you know this library? - https://github.com/Andy4495/TLC591x
> 
> Did not look into the details but it seems to be quite mature.

I will take a look at it

**Comment by Devilscave** [comment]
I tested it, it always aborted with an incomprehensible error, something about file allocation errors, then compiled it for a STM32F1 and saw that it needs 62% of its memory, but the STM32F0 has only half as much memory, so a typical memory shortage error. But I just made an interesting discovery in your profile, the PCA9634 8-channel i2C driver. That sounds almost better than the TLC5917.

**Comment by RobTillaart** [comment]
@Devilscave 
Any progress to report? 
Or did you switch to the PCA9634 completely?

If there are no new insight to report, I close the issue, feel free to reopen if needed.

**Comment by Devilscave** [comment]
No, currently no new results, I have not yet been able to obtain the PCA. I'm still working on the TLC5947 project, but this will soon be in its final stages.
I will now get the chips first and then see how suitable they are for the setup. I will refer to your database and then report back.
In any case, the TLC5917 with the STM32F0 seems to lead to a dead end. I am amazed at the huge amount of extra memory it requires.

**Comment by RobTillaart** [comment]
@Devilscave 
Thanks for the quick reply

> I am amazed at the huge amount of extra memory it requires.

Compiling the TLC5917_demo.ino on an Arduino UNO and the sketch size is 3664. The TLC object itself uses ~10 bytes for internal variables. Runtime it allocates a buffer for the IO lines, one byte per line ==  8 bytes per device. 


Compiling for the Arduino UNO
```
Sketch uses 3664 bytes (11%) of program storage space. Maximum is 32256 bytes.
Global variables use 326 bytes (15%) of dynamic memory, leaving 1722 bytes for local variables. Maximum is 2048 bytes.
```

Compiling for the STM32F0 (I cannot run it) give me 
```
Sketch uses 14008 bytes (85%) of program storage space. Maximum is 16384 bytes.
Global variables use 1228 bytes (29%) of dynamic memory, leaving 2868 bytes for local variables. Maximum is 4096 bytes.
```

So if your application has only about 2K left, which is indeed very little 


----

A sketch with one Serial println(__FILE__) uses 1560 on UNO and 10672 on the STM32F0.  

1. A minimal sketch takes a lot of room 
2. The library uses ~2100 bytes on UNO and ~3500 bytes on STM32. 

The size differences between UNO and STM32 are partly explainable as the STM uses 32 bits for an int where UNO uses 16 bit.

A final test with an empty setup() and empty loop() already uses 50% of PROGMEM. 
```
Sketch uses 8128 bytes (49%) of program storage space. Maximum is 16384 bytes.
```

Conclusion the STM32F0 is only suitable for tiny projects.

**Comment by Devilscave** [comment]
I have now also tried it with some chips, unfortunately the same results with almost all models that came into question. I will now change to size TQFP-32, the board needs to be tidied up anyway and I will use an LGT8F328P. It's 99% compatible with ATMega and still a few better values at a lower price.

**Comment by RobTillaart** [comment]
Can this issue be closed now?

**Comment by RobTillaart** [comment]
As this issue is not a library problem I close this issue.
Feel free to reopen if the library fails on an STM32 with enough memory.
