### ISSUE TITLE
no Port function

### ISSUE THREAD

**Issue by Devilscave** [RobTillaart/TLC5917#4]
I tested the database today, but I don't get any output.
I then worked with the attached TLC5917_Demo.ino and there the same thing, I checked the pins several times and they are connected correctly.
I have subsequently adapted the demo a little to make it shorter and clearer and to simplify the output for me.
The serial output works.

```
#include "TLC5917.h"

TLC5917 tlc(1,8,9,10,99);//(DEVICES, CLOCK, DATA, LE, OE);

void setup(){
  Serial.begin(115200);
  tlc.begin();
}

void loop(){
  for (int ch = 0; ch < tlc.getChannels(); ch++)
  {
    tlc.setChannel(ch, true);
    Serial.print(ch);
    Serial.print(F(" ON "));
    tlc.write();
    delay(1000);
    tlc.setChannel(ch, false);
    Serial.println(F("-> OFF"));
    tlc.write();
    delay(1000);
  }
}
```

The output in the Serial Monitor looks like this:
```
0 ON -> OFF
1 ON -> OFF
2 ON -> OFF
3 ON -> OFF
4 ON -> OFF
5 ON -> OFF
6 ON -> OFF
7 ON -> OFF
0 ON....
```

But I am not receiving any data/signals to the TLC5917.
The only thing I could measure is a peak with 5V+ on the CLK line when the output for channel 0 is switched ON and OFF in the Serial Monitor, while there is 5V+ on CLK.
I have tested another TLC5917 database, which works with the same port specifications as used in this example. I tested both on an Arduino Nano V3 and on a LGT8F328P, same results on both.

**Comment by Devilscave** [comment]
I have now downloaded the entire project again and replaced the existing one.
Now at least the control works PARTLY!!! 
It only controls up to channel 3, after that I have no more output, until I get 0...1...2 again.

**Comment by RobTillaart** [comment]
Interesting that only 2 channels work.
Need to investigate the code if this knowhow can find some bug.

**Comment by Devilscave** [comment]
There are 3 channels, (0, 1, 2)
I have now replaced the TLC5917 to make sure that I have not killed it in previous tests.
Unfortunately not. With a brand new one out of the box exactly the same game.

**Comment by RobTillaart** [comment]
OK 3 channels out of 8, that triggers a faulty masking (2^3 == 8).
Lets look where code uses masks...

**Comment by Devilscave** [comment]
I have now tested it again with this example, but it is for 7-segment displays, but this one controls all 8 LEDs, presumably with “.” So it can't be my setup.

https://github.com/Andy4495/TLC591x/tree/main/examples/TLC591x_library_example

**Comment by RobTillaart** [comment]
Found 1st bug (there may be more)

Please replace setChannel in .cpp file with this

```cpp
bool TLC5917::setChannel(uint8_t channel, bool on)
{
  if (channel >= _channels) return false;
  if (on) _buffer[channel / 8] |=  (1 << channel);
  else    _buffer[channel / 8] &= ~(1 << channel);
  return true;
}
```

**Comment by RobTillaart** [comment]
IN fact it should be this to support multidevice

```cpp
bool TLC5917::setChannel(uint8_t channel, bool on)
{
  if (channel >= _channels) return false;
  if (on) _buffer[channel / 8] |=  (1 << (channel & 0x07));
  else    _buffer[channel / 8] &= ~(1 << (channel & 0x07));
  return true;
}
```

The function was missing ( ) around  the (channel & 0x07)

**Comment by Devilscave** [comment]
After the first code change :
if channel 0 is now switched off, the computer crashes and resets
With the second code it works.

**Comment by RobTillaart** [comment]
> With the second code it works.

Just to understand it 100%  Does it work for all your 7 segment digits now?

**Comment by Devilscave** [comment]
> Just to understand it 100% Does it work for all your 7 segment digits now?

YES, now it work's. But i don't use 7-Segment, i use a line of 8 LEDs.


I noticed something in your Knight_Rider example.
When the LED runs back and forth like this, it switches off briefly when it reaches the last LED and then switches on again. This indicates an overflow of the display, one channel too many, so to speak.
I patched it by changing line 50 in the example and adding -1 after getChannels().
``  if ((pos == 0) || (pos == tlc.getChannels() -1 ))``

**Comment by RobTillaart** [comment]
Good catch!
I will update the library to include this patch today.

**Comment by Devilscave** [comment]
Thank you for the quick fix.

**Comment by Devilscave** [comment]
Is a dimming function already integrated? As the TLC is capable of 256 dimming levels.

**Comment by RobTillaart** [comment]
> Is a dimming function already integrated? As the TLC is capable of 256 dimming levels.

First thing is to get the working version out there, then we can build upon that.

**Comment by RobTillaart** [comment]
Can you run the performance demo and post the output?
And please mention your board

**Comment by RobTillaart** [comment]
Created develop branch and Pull request as preparation for 0.1.1 version.

**Comment by Devilscave** [comment]
> Können Sie die Performance-Demo ausführen und die Ergebnisse veröffentlichen? Und erwähnen Sie bitte Ihr Board

Arduino NANO V3 (old Bootloader)
TLC5917_LIB_VERSION: 	0.1.0
Channels:		                800
SETCHANNEL TRUE:	2572
SETCHANNEL FALSE:	2848
SETALL TRUE:		        232
WRITE:			        14300


LGT8F328P MiniEVB
TLC5917_LIB_VERSION: 	0.1.0
Channels:		                800
SETCHANNEL TRUE:	1156
SETCHANNEL FALSE:	1294
reset at this point

**Comment by RobTillaart** [comment]
Thanks for testing
Will add those numbers to the example so people can compare!

**Comment by RobTillaart** [comment]
> SETCHANNEL FALSE: 1294
reset at this point

mmm, could that reset be a new bug?

**Comment by Devilscave** [comment]
> > SETCHANNEL FALSE: 1294
> > reset at this point
> 
> mmm, could that reset be a new bug?

i don't no, i changed nothing on the code.

**Comment by RobTillaart** [comment]
It might be an out of memory problem,
You could try it with 10 devices to check.

**Comment by RobTillaart** [comment]
Created an issue for the Special mode including  led intensity - https://github.com/RobTillaart/TLC5917/issues/6

**Comment by RobTillaart** [comment]
@Devilscave 
Created a develop branch and a PR for the special mode,
if you have time, can you please test it with your setup?
Please put your comments in issue #6

Think this issue can be closed as setting leds on/off now works.

**Comment by RobTillaart** [comment]
As the library does the basic led-on-off function, this issue is solved.
Discussing the gain control is done in #6
