### ISSUE TITLE
investigate special mode commands - error and intensity.

### ISSUE THREAD

**Issue by RobTillaart** [RobTillaart/TLC5917#6]
from datasheet 9.4 page 16, 

_The TLC591x provides two operation modes: Normal Mode and Special Mode. Normal mode is used for shifting
LED data into and out of the driver. Special Mode includes two functions: Error Detection and Current Gain
Control._

#### Error Detection

_In the Special Mode phase, the low-voltage-level signal on OE(ED2) can enable output channels and detect the
status of the output current to determine if the driving current level is sufficient. The detected Error Status is
loaded into the 8-bit shift register and shifted out via the pin SDO, synchronous to the CLK signal. The system
controller can read the error status and determine if the LEDs are properly lit._

This function needs to connect the SDO line and read back values. 
For me this has lower priority so will not be implemented yet.

#### Current Gain Control

_In the Special Mode phase, the TLC591x allows users to adjust the output current level by setting a runtime 
programmable Configuration Code. The code is sent into the TLC591x through SDI. The positive pulse of
LE(ED1) latches the code in the shift register into a built-in 8-bit configuration latch, instead of the output latch.
The code affects the voltage at the terminal R-EXT and controls the output-current regulator. The output current
can be finely adjusted by a gain ranging from 1/12 to 127/128 in 256 steps. Therefore, the current skew between
ICs can be compensated within less than 1%. This feature is suitable for white balancing in LED color display
panels._

This is the most important function (imho) of the Special mode, so that needs to be implemented first.

**Comment by Devilscave** [comment]
I am currently struggling to realize individual effects that I used to control with a ULN2003 on 7 LEDs.
But it doesn't work. Every time the status changes, it shifts the signal. I thought the TLC5917 was a smaller version of the TLC5947. Just a simple blinking of all LEDs becomes an alternating blinking, or switching on all LEDs suddenly stops.
But the special mode sounds good to me.

**Comment by Devilscave** [comment]
I have tested the TLC5917_demo_gain.
I don't understand the effect and the function behind it, but here is the result from the serial monitor:

```
TLC5917_LIB_VERSION: 	0.1.2

Channels: 8
MODE:	0
MODE:	1
TIME:	25613
MODE:	0

done...
```

**Comment by Devilscave** [comment]
Here a performace test, but today he work an LGT8F338P
TLC5917_LIB_VERSION: 	0.1.2
Channels:		800
SETCHANNEL TRUE:	1156
SETCHANNEL FALSE:	1296
SETALL TRUE:		108
WRITE:			5508

**Comment by Devilscave** [comment]
When testing the TLC5917_demo.ino, I came across a strange behavior.
I modified the demo a bit to have a closer look at the new tlc.channelCount(). For this I put the “for” loop from the setup into the loop. What I would generally suggest as a change for the demo.
When I comment out
```
  if (tlc.begin() == false)
  {
    Serial.println(“error”);
    while (1);
  }
```
it only controls LEDs 1-7, LED 8 is not controlled and everything is dark at channel 0, which seems to cause a shift forward by one value.  so that 0 is -1, 1=0, 2=1, 3=2.....
After adding a serial output of “ch”, I noticed that it does not control the last of the 8 LEDs and also does not control any in the serial at position 0.

**Comment by RobTillaart** [comment]
@Devilscave 
I have updated the develop branch, build is running

The function has been renamed to **void setSpecialMode()** to be in line with the datasheet.
**getMode()** is in it too, returning 0 or 1.

updated the **TLC5917_demo_gain.ino** example that should use this.
Please update to the latest develop and give it a try.

----

Will look into your last post here.

**Comment by RobTillaart** [comment]
> When testing the TLC5917_demo.ino, I came across a strange behavior. I modified the demo a bit to have a closer look at the new tlc.channelCount(). For this I put the “for” loop from the setup into the loop. What I would generally suggest as a change for the demo. When I comment out
> 
> ```
>   if (tlc.begin() == false)
>   {
>     Serial.println(“error”);
>     while (1);
>   }
> ```
> 
> it only controls LEDs 1-7, LED 8 is not controlled and everything is dark at channel 0, which seems to cause a shift forward by one value. so that 0 is -1, 1=0, 2=1, 3=2..... After adding a serial output of “ch”, I noticed that it does not control the last of the 8 LEDs and also does not control any in the serial at position 0.

When you comment out the **Begin()** call,   the IO lines are not explicitly set as OUTPUT and to their initial state.

**Comment by RobTillaart** [comment]
@Devilscave 
Did you make progress with your project (or the PCA9634?)

Today I worked on the setting of the gain (special mode) implementing extra functions and two new examples.
Still no hardware for testing, saw the **TLC5917IN** chip that I can test in a breadboard only at Mouser for 1.56 a piece with 20 euro for post and package.

In short I will release the new code as a 0.1.2 version later today. When I merge that code this issue will be closed.
Feel free to reopen if you still try to get the chip working.

**Comment by Devilscave** [comment]
I would like to test it for you, currently somewhat limited in time due to an upcoming move and completion of my other project. But I am looking ahead with your library
